apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: umb-service
  namespace: argocd
spec:
  destination:
    namespace: umb
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  project: default
  source:
    path: umbrelachart
    repoURL: https://github.com/harishzones2016/testrepo.git
    targetRevision: HEAD
