apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluegreen-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/harishzones2016/testrepo.git
    targetRevision: HEAD
    path: ./manifests/bluegreen

  destination:
    server: https://kubernetes.default.svc
    namespace: bluegreen

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
