apiVersion: v1
kind: Service
metadata:
  labels:
    app: blue-deployment
  name: blue-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: green-deployment
  type: NodePort
