apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: green-deployment
  name: green-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: green-deployment
  template:
    metadata:
      labels:
        app: green-deployment
    spec:
      containers:
      - image: adamtravis/rollouts:green
        name: rollouts
