apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.deployment.containerPort }}
    protocol: TCP
    targetPort: {{ .Values.deployment.containerPort }}
  selector:
    app: {{ .Values.name }} 
