apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-pod
  name: nginx-pod
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  containers:
  - image: nginx
    name: nginx-pod
    env:
    - name: HARISH
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: username
    - name: MAA
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password       

