apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
      - cluster: cluster1
        url: https://kubernetes.default.svc 
      - cluster: cluster2
        url: https://192.168.1.15:6443  
  template:
    metadata:
      name: '{{cluster}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/harishzones2016/testrepo.git
        targetRevision: HEAD
        path: applicationsetexample/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: guestbook
