apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-system-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"    # Set to true for using managed identity
#    userAssignedIdentityID: "c73bf6f0-a78c-44ed-94b8-196d01f5f926"      # Use ClientID not principal id
    clientID: "349b9925-7609-4e83-9fed-41027082de9d"
    keyvaultName: maavault420
    cloudName: "AzurePublicCloud"                   # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: ExampleSecret
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
    tenantId: 71c3e719-d710-41f2-a77d-02c4ee99cf19     # The tenant ID of the key vault(Directory ID)
