apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: red-deployment
  name: red-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: red-deployment
  template:
    metadata:
      labels:
        app: red-deployment
    spec:
      containers:
      - image: adamtravis/rollouts:red
        name: rollouts
