name: Build and Push Docker Image

on:
  push:
    branches:
      - none
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: acr42001.azurecr.io  # name of Docker Hub ID
      IMAGE_NAME: nginx
      IMAGE_TAG: ${{ github.run_number }} # $GITHUB_RUN_NUMBER
      CLUSTER_NAME: aks1
      RESOURSE_GROUP: tutorial


    steps:
    - name: Checkout code
      uses: actions/checkout@v2

#    - name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: acr42001.azurecr.io
        username: ${{ secrets.DOCKER_USERNAME1 }}
        password: ${{ secrets.DOCKER_PASSWORD1 }}

    - name: Build Docker image
      run: |
        docker build --file ./Docker/Dockerfile -t acr42001.azurecr.io/nginx:${{ github.run_number }} .

    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.27.0' # default is latest stable
    
    - name: Kubernetes Set Context
      uses: Azure/k8s-set-context@v3.0
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG }}
        
    - name: Run a multi-line script
      run: |
        kubectl create secret docker-registry harishsecret \
        --docker-server=acr42001.azurecr.io \
        --docker-username=${{ secrets.HARISH1 }} \
        --docker-password=${{ secrets.HARISH2 }} \
        --docker-email=h.n@gmail.com \
        --dry-run=client -o yaml |kubectl apply -f -    
    
    - uses: cschleiden/replace-tokens@v1
      with:
        files: '["testcicd.yaml"]'
        tokenPrefix: __ # optional, default is #{
        tokenSuffix: __ # optional, default is }#
      env:
        DOCKER_REPOSITORY: ${{ env.DOCKER_REPOSITORY }}
        IMAGE_NAME: ${{ env.IMAGE_NAME }}
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
    
    - name: Display
      run: |
        cat testcicd.yaml
    - name: Run
      run: |
        kubectl apply -f testcicd.yaml
    

    - name: Push Docker image
      run: |
        docker push acr42001.azurecr.io/nginx:${{ github.run_number }}
