name: Deploy to Azure

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.4.0"  # Specify the version you want to use
      - name: Terraform Init
        run: terraform init
        working-directory: aks  # Specifies the directory containing Terraform configurations

      - name: Terraform Plan
        run: terraform plan
        working-directory: aks  # Specifies the directory containing Terraform configurations

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: aks  # Specifies the directory containing Terraform confi
