#on: [push]
#name: Linux_Container_Workflow
name: containers
on:
  push:
    branches: none # [ main ]
       
  pull_request:
    branches: none # [ main ]
      
     
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
          
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
 #     - name: 'Build and push image'
 #       uses: azure/docker-login@v1
 #       with:
 #         login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
 #         username: ${{ secrets.REGISTRY_USERNAME }}
 #         password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
#      - name: Build and push Docker image
#        run: |
#          docker buildx build -f ./Docker/Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/kopal:${{ github.sha }} .
#          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/kopal:${{ github.sha }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: Docker
          push: true
          tags: harishnarang2018/kopal:${{ github.sha }}
      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: h
          dns-name-label: nginxbhai
          image: harishnarang2018/kopal:${{ github.sha }}
          registry-login-server: docker.io
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: aci-sampleapp
          location: 'west us'
