#on: [push]
#name: Linux_Container_Workflow

 name: containers
  on:
    push:
      branches: none # [ main ]
       
    pull_request:
      branches: none # [ main ]
      
     
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
