name: "01_IAMRoles"
on:
  workflow_dispatch:

jobs:
  Plan_Uat:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/aws_tf_plan.yml
    with:
      path: ./IAMRoles
      region: ap-south-1
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_REGION }}
  Apply_Plan:
    needs: Plan_Uat       
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/aws_tf_apply.yml
    with:
      path: ./IAMRoles
      region: ap-south-1
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_REGION }}       
