name: Kubernetes Deploy

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

env:
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create kubeconfig
        run: |
#         mkdir ${HOME}/.kube
          echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/tmp/config
          export KUBECONFIG=/tmp/config  

      - name: Run a multi-line script
        run: |
          echo kubectl
          kubectl apply -f nginxser.yaml

           
