name: Kubernetes Test

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

#env:
#  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.24.0' # default is latest stable
        id: install  
      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
          context: kind-kindcluster
      - name: Run a multi-line script
        run: |
           kubectl config get-contexts
           kubectl version
           kubectl create secret generic harishsecret \
           --from-literal=harish1=${{ secrets.harish1 }} \
           --from-literal=harish2=${{ secrets.harish2 }} \
           --dry-run=client -o yaml |kubectl apply -f -
      - name: Run a multi-line script
        run: |
          echo kubectl
          kubectl apply -f nginxser.yaml
      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '_{_'
          tokenSuffix: '_}_'
          files: '["replacedeployment.yaml","replaceservice.yaml"]'
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}
          IMAGE: ${{ vars.IMAGE }}
          REPLICAS: ${{ vars.REPLICAS }} 
      
      - name : Display
        run: |
          cat replacedeployment.yaml
          cat replaceservice.yaml     
