name: 'Workflow calling'

on:
  push:
    branches:
      - none

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/workflowcallexample.yml
    with:
      TERRAFORM_VERSION: '1.1.9'
      path: 'aks'
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SP_CLIENT_SECRET: ${{ secrets.AZURE_SP_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
       
     
